### PR TITLE
Improve CLI

### LINKED ISSUE #152: Include CLI within the package
It would be nice to make the CLI generally accessible from inside the package, so the user doesn't have to worry about having the code set up in a certain way, so rather than having to run `python selene_cli.py`, you always have a function available in the bash called `selene_sdk`. I will send a PR that does this and we can discuss further if you agree this is nice for users.

### PR DESCRIPTION
**Pull request by cthoyt**
#### Reference Issues/PRs

Closes #152

#### What does this implement/fix? Explain your changes.

This PR does several things to improve the CLI:

1. Replaces `docopt` with `click` (it's much easier to work with)
2. puts the `selene_cli.py` inside the package as `cli.py`
3. exposes the CLI using `__main__.py` so it can be run with `python -m selene_sdk`
4. exposes the CLI using the entry_points kwarg in `setup.py` so it can be run in the shell as `selene_sdk`
5. Improve the documentation related to the CLI to make this clear to anyone reading it later

Even though it switched from docopt to click, and also the location moved, everything should continue working exactly the same way. Click auto-generates the documentation for the CLI and I posit is better than docopt, but if you don't agree, I could also change it back.

Happy hacktoberfest / greetings from Germany!

#### What testing did you do to verify the changes in this PR?

It still does the same as before, now with just a slicker interface!

### CODE REVIEW

**Comment by kathyxchen** [comment]
@cthoyt Thank you so much for submitting this PR! I completely agree with the comments you made in the corresponding issue - it's a change we hadn't prioritized but will make the user experience of the library so much better, this is really awesome. :) I'll be sure to review your PR sometime this week.

**Review by kathyxchen — CHANGES_REQUESTED** [review]
Thank you again for this contribution! I have one minor ask - can you add `click` (with whatever version you are using) to the `selene-gpu.yml` and `selene-cpu.yml` conda environment? Just because some people will only use Selene locally (i.e. without `setup.py install` or `conda install`). I think we can also remove `selene-gpu-snapshot.yml` as well since the other two files are more usable. LGTM otherwise. :) I'll approve and push after those changes are made!

**Comment by cthoyt** [comment]
Done in https://github.com/cthoyt-forks-and-packages/selene/commit/58cf55ffa1f7a3d7391daef31cf64f15595cf618, https://github.com/cthoyt-forks-and-packages/selene/commit/e732528463e150f11cccfaf9882d5b1e784e82ce, and https://github.com/cthoyt-forks-and-packages/selene/commit/1aff5e22893abf899b3b69759b9f219353aee1ca. Let me know if that's sufficient

**Review by kathyxchen — APPROVED** [review]
LGTM! Thank you so much for your contribution!

**Pull request merged**
