### PR TITLE
Preliminary support for regression models

### PR DESCRIPTION
**Pull request by evancofer**
Added preliminary support for regression models (using `MatFileSampler`) and user-specified evaluation metrics.

### CODE REVIEW

**Comment by kathyxchen** [comment]
Looks good so far! Just add an example of how to pass in `metrics` via config file (I think you already have this on your to-do list). 
I'll update my config file document after we get your PR pushed to master.

**Comment by evancofer** [comment]
Which tutorial do you recommend adding it to?

**Comment by kathyxchen** [comment]
Probably in the getting started tutorial. You can pass in the default ROC AUC/AUPRC functions---it would just be there to show that the `metrics` parameter exists and how easy it would be to pass in some other metrics.

**Comment by evancofer** [comment]
@kathyxchen This is ready to be merged after you look through it.

**Pull request merged**
