### PR TITLE
[WIP] Wrapping multiple trained models to concatenate model predictions 

### PR DESCRIPTION
**Pull request by kathyxchen**
#### Reference Issues/PRs

Main changes are based on internal discussions. I also include a bugfix addressing issue #118. 

#### What does this implement/fix? Explain your changes.
Add a wrapper class and some edits to the API to allow users to pass in multiple trained model paths and get a single vector of predictions concatenating all the different model predictions.

All models must take in the same sequence length and input dimensions (i.e. 4-D lua-trained vs 3-D)

Also fix handling single-entry bed files for `get_predictions_for_bed_file`.

#### What testing did you do to verify the changes in this PR?
Use this wrapper on a few different pairs of trained models.

Ran `get_predictions_for_bed_file` on a few different BED file examples (along with single-entry bed file).

### CODE REVIEW

**Comment by kathyxchen** [comment]
Example of how the multi model wrapper should be used

```
from selene_sdk.predict import AnalyzeSequences
from selene_sdk.sequences import Genome
from selene_sdk.utils import MultiModelWrapper
from selene_sdk.utils import load_features_list

from example_model import ExampleModel

model = MultiModelWrapper([ExampleModel(100), ExampleModel(10)], concat_dim=1)
paths = [em100_path, em10_path]
features = load_features_list(em110_total_features_path)
genome = Genome(genome_path)
predict = AnalyzeSequences(
    model, paths, seq_len, features, reference_sequence=genome)
```

**Comment by kathyxchen** [comment]
@aaronkw If you have some time, could you review the changes in this PR? I'd like to get this in and then make the next release.

I have a few to-do's (you won't need to review) related to improving/adding documentation around this

**Comment by aaronkw** [comment]
LGTM

**Comment by kathyxchen** [comment]
Thank you @aaronkw!

**Pull request merged**
